name: Move issues by status and priority
on:
 issues:
  types:
    - labeled
    - unlabeled
    - edited

jobs:
  move-by-status:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue based on status label
        uses: bishalrai96/Project_Card_Automation@master
        with:
          label: "Status: In Progress"
          column: "In Progress"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
  move-by-priority:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue based on priority label
        uses: bishalrai96/Project_Card_Automation@master
        with:
          label: "Priority: Low"
          column: "Low"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
