name: Move issues by status and priority
on:
 issues:
  types:
    - labeled
    - unlabeled
    - edited

jobs:
  move-by-status:
    runs-on: ubuntu-latest
    steps:
      - name: Determine column
        id: determine-column
        run: |
          if [[ $GITHUB_EVENT_NAME == 'labeled' ]]; then
            case $GITHUB_EVENT_LABEL_NAME in
              "Status: Dropped") echo "column=Dropped" >> $GITHUB_OUTPUT;;
              "Status: Confirmed") echo "column=Confirmed" >> $GITHUB_OUTPUT;;
              "Status: In Progress") echo "column=In Progress" >> $GITHUB_OUTPUT;;
              "Status: Done") echo "column=Done" >> $GITHUB_OUTPUT;;
              *) echo "column=Backlog" >> $GITHUB_OUTPUT;;
            esac
          else
            echo "column=Backlog" >> $GITHUB_OUTPUT
          fi

      - name: Move issue based on status label
        uses: bishalrai96/Project_Card_Automation@master
        with:
          label: "Status: In Progress"
          column: "In Progress"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
  move-by-priority:
    runs-on: ubuntu-latest
    steps:
      - name: Determine priority column
        id: determine-priority-column
        run: |
          if [[ $GITHUB_EVENT_NAME == 'labeled' ]]; then
            case $GITHUB_EVENT_LABEL_NAME in
            "Priority: Critical") echo "column=Critical" >> $GITHUB_OUTPUT;;
            "Priority: High") echo "column=High" >> $GITHUB_OUTPUT;;
            "Priority: Long-term plans") echo "column=Long-term Plans" >> $GITHUB_OUTPUT;;
            "Priority: Low") echo "column=Low" >> $GITHUB_OUTPUT;;
            "Priority: Medium") echo "column=Medium" >> $GITHUB_OUTPUT;;
            *) echo "column=" >> $GITHUB_OUTPUT
          esac
          else
            echo "column=" >> $GITHUB_OUTPUT
          fi
      - name: Move issue based on priority label
        if: steps.determine-priority-column.outputs.column != ''
        uses: bishalrai96/Project_Card_Automation@master
        with:
          label: "Priority: Low"
          column: "Low"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
